driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.6
    run_list: apt::default
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: ubuntu-16.04
  - name: windows-2012r2-standart
    driver: windows-2012r2-standart
      box: chef/windows-server-2012r2-standart # private box in Chef's Atlas account
  - name: windows-2008r2-standart
    driver: windows-2008r2-standart
      box: chef/windows-server-2008r2-standart # private box in Chef's Atlas account

suites:
- name: default
  run_list:
    - recipe[erlang]

- name: gui_tools
  run_list:
    - recipe[erlang]
  attributes:
    erlang:
      gui_tools: true
  excludes:
    - centos-6.8
    - centos-7.3
    - fedora-25

- name: esl
  run_list:
    - recipe[erlang::esl]
  excludes:
    - fedora-25
    - opensuse-13.2
    - opensuse-42.2

- name: source
  run_list:
    - recipe[erlang::source]
  excludes:
    -  windows-2012r2-standart
    -  windows-2008r2-standart
